server {
    # Make sure this file is LF (*not* CRLF) and UTF-8 (*not* UTF-8 BOM)
    listen 5173;
    listen [::]:5173;
    server_name _;

    client_max_body_size 50M;

    root /usr/share/nginx/html;
    index index.html;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;

    access_log /var/log/nginx/access.log combined;

    location /api/ {
        rewrite ^/api/(.*)$ /api/$1 break;
        proxy_pass https://api.shelfie.georgesheppard.dev/;
        proxy_ssl_server_name on;
        proxy_ssl_name api.shelfie.georgesheppard.dev;
        proxy_set_header Host api.shelfie.georgesheppard.dev;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
